# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37c1795d1b567d4c2f1dae6c4836eb58ad2a5d24e748b6655f6f70805095ecc4255cd94b8195589c4fded6901fff00c1d0cd6329d1e3985e80bcc55da5894b98

test:
  secret_key_base: 79482a333c252a942fff9fc8ece2d36fbc8bdfe36584d8827add2da3e62d0825ee1dbf81c1fc2956f6a206af5d6019ff5387cc81f9559b2673670a8fd46c79b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
